server:
  port: 9999

spring:

  jwt:
    secret: ${JWT_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

    exp:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url:  ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
