server:
  port: 9999

spring:

  jwt:
    secret: ${JWT_SECRET:qwertyuiopasdfghjkl1234567890}
    header: ${JWT_HEADER:root}
    prefix: ${JWT_PREFIX:Secure}

    exp:
      access: ${JWT_ACCESS:1480849147370}
      refresh: ${JWT_REFRESH:1480849147370}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url:  jdbc:mysql://localhost:3306/unknown?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 2513
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}


  mail:
    host: smtp.gmail.com
    port: 587
    username: eogus_2513@dsm.hs.kr
    password: eogus@2513
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
