spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url:  ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    accessExp: ${JWT_ACCESS}
    refreshExp: ${JWT_REFRESH}